// inventory/vue/src/components/cell-renderers/stockCellRenderer.vue
<script setup>
import { defineProps } from "vue";

const { params } = defineProps(["params"]);
const { data } = params;
</script>

<template>
  <div class="stock">
    <span>{{ data.available }}</span>
    &nbsp;<span class="stockText">Stock /</span>&nbsp;
    <span class="variantsText">{{ `${data.variants} Variants` }}</span>
  </div>
</template>

<style>
.stockText {
  opacity: 0.7;
}

.variantsText {
  opacity: 0.7;
}
</style>

// inventory/angular/src/app/inventory-example/cell-renderer/stock-cell-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from '@ag-grid-community/angular';
import { ICellRendererParams } from '@ag-grid-community/core';

@Component({
  selector: 'stock-cell-renderer',
  standalone: true,
  template: `
    <div class="stock">
      <span>{{ available }}</span>
      &nbsp;<span class="stockText">Stock /</span>&nbsp;
      <span class="variantsText">{{ variants }} Variants</span>
    </div>
  `,
  styles: [
    `
      .stockText {
        opacity: 0.7;
      }

      .variantsText {
        opacity: 0.7;
      }
    `,
  ],
})
export class StockCellRenderer implements ICellRendererAngularComp {
  public available: number | string = '';
  public variants: number = 0;

  agInit(params: ICellRendererParams): void {
    this.available = params.data.available;
    this.variants = params.data.variants;
  }

  refresh(params: ICellRendererParams): boolean {
    this.available = params.data.available;
    this.variants = params.data.variants;
    return true;
  }
}
