// finance/react/src/FinanceExample.tsx
import { AgChartsEnterpriseModule } from "ag-charts-enterprise";
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";

import {
  type ColDef,
  colorSchemeDark,
  type GetRowIdFunc,
  type GetRowIdParams,
  type GridSizeChangedEvent,
  ModuleRegistry,
  themeQuartz,
  type ValueFormatterFunc,
  type ValueGetterParams,
} from "ag-grid-community";
import { AllEnterpriseModule } from "ag-grid-enterprise";
import { AgGridReact } from "ag-grid-react";

import styles from "./FinanceExample.module.css";
import { getData } from "./data";
import { getTickerCellRenderer } from "./renderers/getTickerCellRenderer";
import { sparklineTooltipRenderer } from "./renderers/sparklineTooltipRenderer";

export interface Props {
  isDarkMode?: boolean;
  gridHeight?: number | null;
  isSmallerGrid?: boolean;
  updateInterval?: number;
  enableRowGroup?: boolean;
}

const DEFAULT_UPDATE_INTERVAL = 60;
const PERCENTAGE_CHANGE = 20;
type Breakpoint = "small" | "medium" | "medLarge" | "large" | "xlarge";
type ColWidth = number | "auto";

const BREAKPOINT_CONFIG: Record<
  Breakpoint,
  {
    breakpoint?: number;
    columns: string[];
    tickerColumnWidth: ColWidth;
    timelineColumnWidth: ColWidth;
    hideTickerName?: boolean;
  }
> = {
  small: {
    breakpoint: 500,
    columns: ["ticker", "timeline"],
    tickerColumnWidth: "auto",
    timelineColumnWidth: "auto",
    hideTickerName: true,
  },
  medium: {
    breakpoint: 850,
    columns: ["ticker", "timeline", "totalValue"],
    tickerColumnWidth: 180,
    timelineColumnWidth: 140,
    hideTickerName: true,
  },
  medLarge: {
    breakpoint: 900,
    tickerColumnWidth: 340,
    timelineColumnWidth: 140,
    columns: ["ticker", "timeline", "totalValue", "p&l"],
  },
  large: {
    breakpoint: 1100,
    tickerColumnWidth: 340,
    timelineColumnWidth: 140,
    columns: ["ticker", "timeline", "totalValue", "p&l"],
  },
  xlarge: {
    tickerColumnWidth: 340,
    timelineColumnWidth: 140,
    columns: [
      "ticker",
      "timeline",
      "totalValue",
      "p&l",
      "instrument",
      "price",
      "quantity",
    ],
  },
};

ModuleRegistry.registerModules([
  AllEnterpriseModule.with(AgChartsEnterpriseModule),
]);

const numberFormatter: ValueFormatterFunc = ({ value }) => {
  const formatter = new Intl.NumberFormat("en-US", {
    style: "decimal",
    maximumFractionDigits: 2,
  });
  return value == null ? "" : formatter.format(value);
};

export const FinanceExample: React.FC<Props> = ({
  isDarkMode = false,
  gridHeight = null,
  isSmallerGrid,
  updateInterval = DEFAULT_UPDATE_INTERVAL,
  enableRowGroup,
}) => {
  const [rowData, setRowData] = useState(getData());
  const gridRef = useRef<AgGridReact>(null);
  const gridWrapperRef = useRef<HTMLDivElement>(null);
  const intervalId = useRef<ReturnType<typeof setInterval>>();
  const [breakpoint, setBreakpoint] = useState<Breakpoint>("xlarge");

  const createUpdater = useCallback(() => {
    return setInterval(() => {
      setRowData((rowData) =>
        rowData.map((item) => {
          const isRandomChance = Math.random() < 0.1;

          if (!isRandomChance) {
            return item;
          }
          const rnd = (Math.random() * PERCENTAGE_CHANGE) / 100;
          const change = Math.random() > 0.5 ? 1 - rnd : 1 + rnd;
          const price =
            item.price < 10
              ? item.price * change
              : // Increase price if it is too low, so it does not hang around 0
                Math.random() * 40 + 10;

          const timeline = item.timeline
            .slice(1, item.timeline.length)
            .concat(Number(price.toFixed(2)));

          return {
            ...item,
            price,
            timeline,
          };
        }),
      );
    }, updateInterval);
  }, [updateInterval]);

  useEffect(() => {
    const element = gridWrapperRef.current;
    if (!element) {
      return;
    }

    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) {
        clearInterval(intervalId.current);
        intervalId.current = createUpdater();
      } else {
        clearInterval(intervalId.current);
      }
    });

    observer.observe(element);

    return () => {
      observer.disconnect();
      clearInterval(intervalId.current);
    };
  }, [createUpdater]);

  const colDefs = useMemo<ColDef[]>(() => {
    const breakpointConfig = BREAKPOINT_CONFIG[breakpoint];
    const tickerWidthDefs =
      breakpointConfig.tickerColumnWidth === "auto"
        ? { flex: 1 }
        : {
            initialWidth: breakpointConfig.tickerColumnWidth as number,
            minWidth: breakpointConfig.tickerColumnWidth as number,
          };
    const timelineWidthDefs =
      breakpointConfig.timelineColumnWidth === "auto"
        ? { flex: 1 }
        : {
            initialWidth: breakpointConfig.timelineColumnWidth as number,
            minWidth: breakpointConfig.timelineColumnWidth as number,
          };
    const allColDefs: ColDef[] = [
      {
        field: "ticker",
        cellRenderer: getTickerCellRenderer(
          Boolean(breakpointConfig.hideTickerName),
        ),
        ...tickerWidthDefs,
      },
      {
        headerName: "Timeline",
        field: "timeline",
        sortable: false,
        filter: false,
        cellRenderer: "agSparklineCellRenderer",
        cellRendererParams: {
          sparklineOptions: {
            type: "bar",
            direction: "vertical",
            axis: {
              strokeWidth: 0,
            },
            tooltip: {
              renderer: sparklineTooltipRenderer,
            },
          },
        },
        ...timelineWidthDefs,
      },
      {
        field: "instrument",
        cellDataType: "text",
        type: "rightAligned",
        minWidth: 100,
        initialWidth: 100,
      },
      {
        colId: "p&l",
        headerName: "P&L",
        cellDataType: "number",
        filter: "agNumberColumnFilter",
        type: "rightAligned",
        cellRenderer: "agAnimateShowChangeCellRenderer",
        valueGetter: ({ data }: ValueGetterParams) =>
          data && data.quantity * (data.price / data.purchasePrice),
        valueFormatter: numberFormatter,
        aggFunc: "sum",
        minWidth: 140,
        initialWidth: 140,
      },
      {
        colId: "totalValue",
        headerName: "Total Value",
        type: "rightAligned",
        cellDataType: "number",
        filter: "agNumberColumnFilter",
        valueGetter: ({ data }: ValueGetterParams) =>
          data && data.quantity * data.price,
        cellRenderer: "agAnimateShowChangeCellRenderer",
        valueFormatter: numberFormatter,
        aggFunc: "sum",
        minWidth: 160,
        initialWidth: 160,
      },
    ];

    if (!isSmallerGrid) {
      allColDefs.push(
        {
          field: "quantity",
          cellDataType: "number",
          type: "rightAligned",
          valueFormatter: numberFormatter,
          maxWidth: 75,
        },
        {
          headerName: "Price",
          field: "purchasePrice",
          cellDataType: "number",
          type: "rightAligned",
          valueFormatter: numberFormatter,
          maxWidth: 75,
        },
      );
    }

    return allColDefs.filter(
      (cDef) =>
        breakpointConfig.columns.includes(cDef.field!) ||
        breakpointConfig.columns.includes(cDef.colId!),
    );
  }, [breakpoint, isSmallerGrid]);

  const defaultColDef: ColDef = useMemo(
    () => ({
      flex: 1,
      filter: true,
      enableRowGroup,
      enableValue: true,
    }),
    [enableRowGroup],
  );

  const getRowId = useCallback<GetRowIdFunc>(
    ({ data: { ticker } }: GetRowIdParams) => ticker,
    [],
  );

  const onGridSizeChanged = useCallback((params: GridSizeChangedEvent) => {
    if (params.clientWidth < BREAKPOINT_CONFIG.small.breakpoint!) {
      setBreakpoint("small");
    } else if (params.clientWidth < BREAKPOINT_CONFIG.medium.breakpoint!) {
      setBreakpoint("medium");
    } else if (params.clientWidth < BREAKPOINT_CONFIG.medLarge.breakpoint!) {
      setBreakpoint("medLarge");
    } else if (params.clientWidth < BREAKPOINT_CONFIG.large.breakpoint!) {
      setBreakpoint("large");
    } else {
      setBreakpoint("xlarge");
    }
  }, []);

  const statusBar = useMemo(
    () => ({
      statusPanels: [
        { statusPanel: "agTotalAndFilteredRowCountComponent" },
        { statusPanel: "agTotalRowCountComponent" },
        { statusPanel: "agFilteredRowCountComponent" },
        { statusPanel: "agSelectedRowCountComponent" },
        { statusPanel: "agAggregationComponent" },
      ],
    }),
    [],
  );

  const theme = useMemo(() => {
    return isDarkMode ? themeQuartz.withPart(colorSchemeDark) : themeQuartz;
  }, [isDarkMode]);

  const chartThemes = isDarkMode ? ["ag-default-dark"] : ["ag-default"];
  return (
    <div
      ref={gridWrapperRef}
      style={gridHeight ? { height: gridHeight } : {}}
      className={`${styles.grid} ${gridHeight ? "" : styles.gridHeight}`}
    >
      <AgGridReact
        theme={theme}
        chartThemes={chartThemes}
        ref={gridRef}
        getRowId={getRowId}
        rowData={rowData}
        columnDefs={colDefs}
        defaultColDef={defaultColDef}
        cellSelection={true}
        enableCharts
        rowGroupPanelShow={enableRowGroup ? "always" : "never"}
        suppressAggFuncInHeader
        groupDefaultExpanded={-1}
        statusBar={statusBar}
        onGridSizeChanged={onGridSizeChanged}
      />
    </div>
  );
};

// finance/vue/src/components/FinanceExample.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, withDefaults } from "vue";

import { AgChartsEnterpriseModule } from "ag-charts-enterprise";
import { AgGridVue } from "ag-grid-vue3";
import {
  colorSchemeDark,
  type ColDef,
  type GetRowIdParams,
  type GridSizeChangedEvent,
  ModuleRegistry,
  themeQuartz,
  type ValueFormatterFunc,
  type ValueGetterParams,
} from "ag-grid-community";
import { AllEnterpriseModule } from "ag-grid-enterprise";

import { getData } from "./data";

import TickerCellRenderer from "./renderers/tickerCellRenderer.vue";
import { sparklineTooltipRenderer } from "./renderers/sparklineTooltipRenderer";

const DEFAULT_UPDATE_INTERVAL = 60;
const PERCENTAGE_CHANGE = 20;
type Breakpoint = "small" | "medium" | "medLarge" | "large" | "xlarge";
type ColWidth = number | "auto";

const BREAKPOINT_CONFIG: Record<
  Breakpoint,
  {
    breakpoint?: number;
    columns: string[];
    tickerColumnWidth: ColWidth;
    timelineColumnWidth: ColWidth;
    hideTickerName?: boolean;
  }
> = {
  small: {
    breakpoint: 500,
    columns: ["ticker", "timeline"],
    tickerColumnWidth: "auto",
    timelineColumnWidth: "auto",
    hideTickerName: true,
  },
  medium: {
    breakpoint: 850,
    columns: ["ticker", "timeline", "totalValue"],
    tickerColumnWidth: 180,
    timelineColumnWidth: 140,
    hideTickerName: true,
  },
  medLarge: {
    breakpoint: 900,
    tickerColumnWidth: 340,
    timelineColumnWidth: 140,
    columns: ["ticker", "timeline", "totalValue", "p&l"],
  },
  large: {
    breakpoint: 1100,
    tickerColumnWidth: 340,
    timelineColumnWidth: 140,
    columns: ["ticker", "timeline", "totalValue", "p&l"],
  },
  xlarge: {
    tickerColumnWidth: 340,
    timelineColumnWidth: 140,
    columns: [
      "ticker",
      "timeline",
      "totalValue",
      "p&l",
      "instrument",
      "price",
      "quantity",
    ],
  },
};

const props = withDefaults(
  defineProps<{
    isDarkMode?: boolean;
    isSmallerGrid?: boolean;
    updateInterval?: number;
    enableRowGroup?: boolean;
  }>(),
  {
    updateInterval: DEFAULT_UPDATE_INTERVAL,
  },
);

ModuleRegistry.registerModules([
  AllEnterpriseModule.with(AgChartsEnterpriseModule),
]);

const rowData = ref(getData());
const gridWrapper = ref<HTMLDivElement | null>(null);
const intervalId = ref<ReturnType<typeof setInterval>>();
const breakpoint = ref<Breakpoint>("xlarge");
let observer: IntersectionObserver | undefined;

const numberFormatter: ValueFormatterFunc = (params) => {
  const formatter = new Intl.NumberFormat("en-US", {
    style: "decimal",
    maximumFractionDigits: 2,
  });
  return params.value == null ? "" : formatter.format(params.value);
};

function getRowId(params: GetRowIdParams) {
  return params.data.ticker;
}

const createUpdater = () => {
  return setInterval(() => {
    rowData.value = rowData.value.map((item) => {
      const isRandomChance = Math.random() < 0.1;

      if (!isRandomChance) {
        return item;
      }
      const rnd = (Math.random() * PERCENTAGE_CHANGE) / 100;
      const change = Math.random() > 0.5 ? 1 - rnd : 1 + rnd;
      const price =
        item.price < 10
          ? item.price * change
          : // Increase price if it is too low, so it does not hang around 0
            Math.random() * 40 + 10;

      const timeline = item.timeline
        .slice(1, item.timeline.length)
        .concat(Number(price.toFixed(2)));

      return {
        ...item,
        price,
        timeline,
      };
    });
  }, props.updateInterval);
};

const onGridSizeChanged = (params: GridSizeChangedEvent) => {
  if (params.clientWidth < BREAKPOINT_CONFIG.small.breakpoint!) {
    breakpoint.value = "small";
  } else if (params.clientWidth < BREAKPOINT_CONFIG.medium.breakpoint!) {
    breakpoint.value = "medium";
  } else if (params.clientWidth < BREAKPOINT_CONFIG.medLarge.breakpoint!) {
    breakpoint.value = "medLarge";
  } else if (params.clientWidth < BREAKPOINT_CONFIG.large.breakpoint!) {
    breakpoint.value = "large";
  } else {
    breakpoint.value = "xlarge";
  }
};

const colDefs = computed<ColDef[]>(() => {
  const breakpointConfig = BREAKPOINT_CONFIG[breakpoint.value];
  const tickerWidthDefs =
    breakpointConfig.tickerColumnWidth === "auto"
      ? { flex: 1 }
      : {
          initialWidth: breakpointConfig.tickerColumnWidth as number,
          minWidth: breakpointConfig.tickerColumnWidth as number,
        };
  const timelineWidthDefs =
    breakpointConfig.timelineColumnWidth === "auto"
      ? { flex: 1 }
      : {
          initialWidth: breakpointConfig.timelineColumnWidth as number,
          minWidth: breakpointConfig.timelineColumnWidth as number,
        };

  const allColDefs: ColDef[] = [
    {
      field: "ticker",
      cellRenderer: TickerCellRenderer,
      cellRendererParams: {
        hideTickerName: Boolean(breakpointConfig.hideTickerName),
      },
      ...tickerWidthDefs,
    },
    {
      headerName: "Timeline",
      field: "timeline",
      sortable: false,
      filter: false,
      cellRenderer: "agSparklineCellRenderer",
      cellRendererParams: {
        sparklineOptions: {
          type: "bar",
          direction: "vertical",
          axis: {
            strokeWidth: 0,
          },
          tooltip: {
            renderer: sparklineTooltipRenderer,
          },
        },
      },
      ...timelineWidthDefs,
    },
    {
      field: "instrument",
      cellDataType: "text",
      type: "rightAligned",
      minWidth: 100,
      initialWidth: 100,
    },
    {
      colId: "p&l",
      headerName: "P&L",
      cellDataType: "number",
      filter: "agNumberColumnFilter",
      type: "rightAligned",
      cellRenderer: "agAnimateShowChangeCellRenderer",
      valueGetter: ({ data }: ValueGetterParams) =>
        data && data.quantity * (data.price / data.purchasePrice),
      valueFormatter: numberFormatter,
      aggFunc: "sum",
      minWidth: 140,
      initialWidth: 140,
    },
    {
      colId: "totalValue",
      headerName: "Total Value",
      type: "rightAligned",
      cellDataType: "number",
      filter: "agNumberColumnFilter",
      valueGetter: ({ data }: ValueGetterParams) =>
        data && data.quantity * data.price,
      cellRenderer: "agAnimateShowChangeCellRenderer",
      valueFormatter: numberFormatter,
      aggFunc: "sum",
      minWidth: 160,
      initialWidth: 160,
    },
  ];

  if (!props.isSmallerGrid) {
    allColDefs.push(
      {
        field: "quantity",
        cellDataType: "number",
        type: "rightAligned",
        valueFormatter: numberFormatter,
        maxWidth: 75,
      },
      {
        headerName: "Price",
        field: "purchasePrice",
        cellDataType: "number",
        type: "rightAligned",
        valueFormatter: numberFormatter,
        maxWidth: 75,
      },
    );
  }

  return allColDefs.filter(
    (cDef) =>
      breakpointConfig.columns.includes(cDef.field as string) ||
      breakpointConfig.columns.includes(cDef.colId as string),
  );
});

const theme = computed(() => {
  return props.isDarkMode ? themeQuartz.withPart(colorSchemeDark) : themeQuartz;
});
const chartThemes = computed(() =>
  props.isDarkMode ? ["ag-default-dark"] : ["ag-default"],
);
const cellSelection: boolean = true;
const enableCharts: boolean = true;
const rowGroupPanelShow = computed(() =>
  props.enableRowGroup ? "always" : "never",
);
const suppressAggFuncInHeader: boolean = true;
const groupDefaultExpanded = -1;

const defaultColDef = computed<ColDef>(() => ({
  flex: 1,
  filter: true,
  enableRowGroup: props.enableRowGroup,
  enableValue: true,
}));

const statusBar = {
  statusPanels: [
    { statusPanel: "agTotalAndFilteredRowCountComponent" },
    { statusPanel: "agTotalRowCountComponent" },
    { statusPanel: "agFilteredRowCountComponent" },
    { statusPanel: "agSelectedRowCountComponent" },
    { statusPanel: "agAggregationComponent" },
  ],
};

onMounted(() => {
  if (!gridWrapper.value) {
    return;
  }

  observer = new IntersectionObserver(([entry]) => {
    if (entry.isIntersecting) {
      clearInterval(intervalId.value);
      intervalId.value = createUpdater();
    } else {
      clearInterval(intervalId.value);
    }
  });

  observer.observe(gridWrapper.value);
});

onBeforeUnmount(() => {
  observer?.disconnect();
  clearInterval(intervalId.value);
});
</script>

<template>
  <div class="wrapper">
    <div class="container">
      <div ref="gridWrapper" class="grid gridHeight">
        <ag-grid-vue
          :style="{ height: '100%' }"
          :theme="theme"
          :getRowId="getRowId"
          :rowData="rowData"
          :columnDefs="colDefs"
          :defaultColDef="defaultColDef"
          :cellSelection="cellSelection"
          :enableCharts="enableCharts"
          :rowGroupPanelShow="rowGroupPanelShow"
          :suppressAggFuncInHeader="suppressAggFuncInHeader"
          :groupDefaultExpanded="groupDefaultExpanded"
          :statusBar="statusBar"
          :chartThemes="chartThemes"
          @grid-size-changed="onGridSizeChanged"
        >
        </ag-grid-vue>
      </div>
    </div>
  </div>
</template>

<style>
:root {
  --layout-grid-header-height: 32px;
  --layout-grid-margin: 32px;
}

body {
  margin: 0;
}

.grid {
  --ag-value-change-value-highlight-background-color: #44ad4961;
  --ag-value-change-delta-down-color: rgb(255, 0, 92);
  --ag-value-change-delta-up-color: rgb(53, 182, 90);
}

.gridHeight {
  height: calc(
    100vh - var(--layout-grid-header-height) - var(--layout-grid-margin)
  );
  margin: var(--layout-grid-margin);

  @media screen and (max-height: 720px) {
    min-height: 500px;
    padding-bottom: 24px;
  }
}

.ag-theme-quartz-dark .ag-row {
  --ag-row-hover-color: #323a46;
}

@media screen and (max-width: 720px) {
  div.ag-theme-quartz,
  div.ag-theme-quartz-dark {
    --ag-font-size: 12px;
    --ag-grid-size: 6px;
  }
}

.ag-theme-quartz .ag-row-group,
.container {
  width: 100%;
}

.ag-theme-quartz .ag-value-change-value-highlight,
.ag-theme-quartz-dark .ag-value-change-value-highlight {
  padding-left: 6px;
  padding-right: 6px;
  padding-top: 2px;
  padding-bottom: 2px;
  border-radius: 12px;
  margin-left: 4px;
}

.ag-right-aligned-cell {
  font-variant-numeric: tabular-nums;
  letter-spacing: -0.01em;
}

.ticker-name {
  opacity: 0.8;
}
</style>
