// finance/vue/src/components/cell-renderers/tickerCellRenderer.vue
<template>
  <div class="tickerCell">
    <img
      :src="`/example/finance/logos/${data.ticker}.png`"
      style="width: 20px; height: 20px; margin-right: 5px; border-radius: 32px"
    />
    <b class="custom-ticker">{{ data.ticker }}</b>
    <span class="ticker-name">{{ data.name }}</span>
  </div>
</template>

<script setup>
import { defineProps } from "vue";

const { params } = defineProps(["params"]);

const data = params.data;
</script>

// finance/react/src/cell-renderers/TickerCellRenderer.tsx
import type { CustomCellRendererProps } from "@ag-grid-community/react";
import { type FunctionComponent } from "react";

export const TickerCellRenderer: FunctionComponent<CustomCellRendererProps> = ({
  data,
}) => {
  return (
    data && (
      <div>
        <img
          src={`/example/finance/logos/${data.ticker}.png`}
          style={{
            width: "20px",
            height: "20px",
            marginRight: "5px",
            borderRadius: "32px",
          }}
        />
        <b className="custom-ticker">{data.ticker}</b>
        <span className="ticker-name"> {data.name}</span>
      </div>
    )
  );
};
