// finance/vue/src/components/renderers/tickerCellRenderer.vue
<template>
  <div class="tickerCell" style="display: flex; align-items: center; gap: 5px">
    <img
      :src="`/example/finance/logos/${data.ticker}.png`"
      style="width: 20px; height: 20px; border-radius: 32px"
    />
    <b class="custom-ticker">{{ data.ticker }}</b>
    <span class="ticker-name">{{ data.name }}</span>
  </div>
</template>

<script setup>
import { defineProps } from "vue";

const { params } = defineProps(["params"]);

const data = params.data;
</script>

// finance/react/src/renderers/TickerCellRenderer.tsx
import { type FunctionComponent } from "react";

import type { CustomCellRendererProps } from "ag-grid-react";

export const TickerCellRenderer: FunctionComponent<CustomCellRendererProps> = ({
  data,
}) => {
  return (
    data && (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "5px",
        }}
      >
        <img
          src={`/example/finance/logos/${data.ticker}.png`}
          style={{
            width: "20px",
            height: "20px",
            borderRadius: "32px",
          }}
          alt={`${data.name} logo`}
        />
        <b className="custom-ticker">{data.ticker}</b>
        <span className="ticker-name"> {data.name}</span>
      </div>
    )
  );
};
