// hr/angular/src/app/cell-renderers/status-cell-renderer.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";
import type { ICellRendererAngularComp } from "ag-grid-angular";
import type { ICellRendererParams } from "ag-grid-community";

@Component({
  standalone: true,
  selector: "app-status-cell-renderer",
  imports: [CommonModule],
  template: `
    <div class="tag" [ngClass]="statusClass">
      <img
        *ngIf="value === 'paid'"
        class="tick"
        src="/example/hr/tick.svg"
        alt="tick"
      />
      <span>{{ value }}</span>
    </div>
  `,
})
export class StatusCellRendererComponent implements ICellRendererAngularComp {
  value = "";
  statusClass = "";

  agInit(params: ICellRendererParams): void {
    this.value = params.value ?? "";
    this.statusClass = this.value ? `${this.value}Tag` : "";
  }

  refresh(params: ICellRendererParams): boolean {
    this.agInit(params);
    return true;
  }
}

// hr/react/src/cell-renderers/StatusCellRenderer.tsx
import type { CustomCellRendererProps } from "@ag-grid-community/react";
import { type FunctionComponent } from "react";

import styles from "./StatusCellRenderer.module.css";

export const StatusCellRenderer: FunctionComponent<CustomCellRendererProps> = ({
  value,
}) => (
  <div className={`${styles.tag} ${styles[value + "Tag"]}`}>
    {value === "paid" && (
      <img className={styles.tick} src={`/example/hr/tick.svg`} alt="tick" />
    )}
    <span>{value}</span>
  </div>
);
